############################################################
# Launcher for MRS container for the eBioKit
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - ${INSTANCE_PORT_1}, port number for MRS instance
#   - ${ADMIN_EMAIL}, email for admin user
#   - ${ADMIN_PASS}, email for admin user
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-mrs:
      image: fikipollo/mrs:0.9
      container_name: $${INSTANCE_NAME}-mrs
      environment:
        - MRS_ADMIN_EMAIL=${ADMIN_EMAIL}
        - MRS_ADMIN_PASSWORD=${ADMIN_PASS}
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "${INSTANCE_PORT_1}:18090"

    $${INSTANCE_NAME}-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-data
      volumes:
        - ${DATA_LOCATION}/$${INSTANCE_NAME}-data/data:/data
        - ${DATA_LOCATION}/$${INSTANCE_NAME}-data/log:/log
